#include "metrics.h"
#include "protocol.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>
metrics_t g_metrics;
void metrics_reset(void){memset(&g_metrics,0,sizeof(g_metrics));g_metrics.rssi_min=127;g_metrics.rssi_max=-127;g_metrics.rtt_min=UINT32_MAX;}
void metrics_tx_requested(uint16_t s){__atomic_fetch_add(&g_metrics.totals.tx_requested,1,__ATOMIC_RELAXED);if(s<HARNESS_MAX_STREAMS)__atomic_fetch_add(&g_metrics.streams[s].tx,1,__ATOMIC_RELAXED);}
void metrics_tx_submitted(uint16_t s,uint16_t len){(void)s;__atomic_fetch_add(&g_metrics.totals.tx_submitted,1,__ATOMIC_RELAXED);__atomic_fetch_add(&g_metrics.totals.tx_bytes,len,__ATOMIC_RELAXED);}
void metrics_tx_api_failure(void){__atomic_fetch_add(&g_metrics.totals.send_api_failure,1,__ATOMIC_RELAXED);}
void metrics_tx_complete(bool ok){if(ok)g_metrics.totals.send_cb_success++;else g_metrics.totals.send_cb_failure++;}
static void seq_observe(stream_metric_t*m,uint32_t seq){m->rx++;if(!m->init){m->init=true;m->highest=seq;m->bitmap=1;if(seq)m->gaps+=seq;return;}if(seq>m->highest){uint32_t d=seq-m->highest;if(d>1)m->gaps+=(uint64_t)d-1;m->bitmap=d>=64?1:(m->bitmap<<d)|1;m->highest=seq;}else{uint32_t d=m->highest-seq;if(d>=64){m->out_of_order++;return;}uint64_t bit=UINT64_C(1)<<d;if(m->bitmap&bit){m->duplicate++;return;}m->bitmap|=bit;m->out_of_order++;if(m->gaps) m->gaps--;}}
void metrics_rx(const bench_header_t*h,int8_t rssi,uint64_t now){g_metrics.totals.rx_packets++;g_metrics.totals.rx_bytes+=h->packet_len;stream_metric_t*m=&g_metrics.streams[h->stream_id];uint64_t od=m->out_of_order,du=m->duplicate;seq_observe(m,h->seq);g_metrics.totals.out_of_order+=m->out_of_order-od;g_metrics.totals.duplicate+=m->duplicate-du;g_metrics.rssi_count++;g_metrics.rssi_sum+=rssi;if(rssi<g_metrics.rssi_min)g_metrics.rssi_min=rssi;if(rssi>g_metrics.rssi_max)g_metrics.rssi_max=rssi;int idx=rssi+127;if(idx<0)idx=0;if(idx>127)idx=127;g_metrics.rssi_hist[idx]++;if(h->type==PACKET_ECHO&&now>=h->timestamp_us){uint64_t r=now-h->timestamp_us;if(r>UINT32_MAX)r=UINT32_MAX;uint32_t v=(uint32_t)r;if(g_metrics.rtt_seen){uint32_t j=v>g_metrics.last_rtt?v-g_metrics.last_rtt:g_metrics.last_rtt-v;g_metrics.jitter_sum+=j;g_metrics.jitter_count++;if(j>g_metrics.jitter_max)g_metrics.jitter_max=j;}g_metrics.last_rtt=v;g_metrics.rtt_seen++;g_metrics.rtt_sum+=v;g_metrics.rtt_sum_sq+=(long double)v*v;if(v<g_metrics.rtt_min)g_metrics.rtt_min=v;if(v>g_metrics.rtt_max)g_metrics.rtt_max=v;if(g_metrics.rtt_count<RTT_CAPACITY)g_metrics.rtt[g_metrics.rtt_count++]=v;else{uint64_t slot=(h->seq*UINT64_C(2654435761)+h->stream_id)%g_metrics.rtt_seen;if(slot<RTT_CAPACITY)g_metrics.rtt[slot]=v;}}}
void metrics_drop(bool stale,bool invalid){if(stale)g_metrics.totals.stale++;if(invalid)g_metrics.totals.invalid++;}
static int cmp32(const void*a,const void*b){uint32_t x=*(const uint32_t*)a,y=*(const uint32_t*)b;return(x>y)-(x<y);}static uint32_t pct(double q){if(!g_metrics.rtt_count)return 0;size_t i=(size_t)ceil((g_metrics.rtt_count-1)*q);return g_metrics.rtt[i];}
static void u64(cJSON*o,const char*k,uint64_t v){cJSON_AddNumberToObject(o,k,(double)v);}cJSON*metrics_json(void){qsort(g_metrics.rtt,g_metrics.rtt_count,sizeof(uint32_t),cmp32);cJSON*r=cJSON_CreateObject(),*t=cJSON_AddObjectToObject(r,"totals");uint64_t gaps=0;for(int i=0;i<HARNESS_MAX_STREAMS;i++)gaps+=g_metrics.streams[i].gaps;g_metrics.totals.estimated_loss=gaps;
#define A(x) u64(t,#x,g_metrics.totals.x)
A(tx_requested);A(tx_submitted);A(tx_bytes);A(send_cb_success);A(send_cb_failure);A(send_api_failure);A(rx_packets);A(rx_bytes);A(duplicate);A(out_of_order);A(estimated_loss);A(stale);A(invalid);A(queue_drops);
#undef A
uint64_t elapsed=g_metrics.end_us>g_metrics.start_us?g_metrics.end_us-g_metrics.start_us:0;uint64_t requested_pps=g_config.mode==MODE_SATURATION?0:(g_config.mode==MODE_LATENCY_LOAD?(uint64_t)g_config.background_rate+g_config.probe_rate:(uint64_t)g_config.rate_per_stream*g_config.streams);cJSON_AddNumberToObject(t,"elapsed_us",(double)elapsed);cJSON_AddNumberToObject(t,"requested_pps",(double)requested_pps);cJSON_AddNumberToObject(t,"tx_pps",elapsed?g_metrics.totals.tx_submitted*1e6/elapsed:0);cJSON_AddNumberToObject(t,"rx_pps",elapsed?g_metrics.totals.rx_packets*1e6/elapsed:0);cJSON_AddNumberToObject(t,"tx_application_bps",elapsed?g_metrics.totals.tx_bytes*8e6/elapsed:0);cJSON_AddNumberToObject(t,"rx_application_bps",elapsed?g_metrics.totals.rx_bytes*8e6/elapsed:0);cJSON_AddNumberToObject(t,"goodput_bps",elapsed?g_metrics.totals.rx_bytes*8e6/elapsed:0);
cJSON*rs=cJSON_AddObjectToObject(r,"rssi");cJSON_AddNumberToObject(rs,"min",g_metrics.rssi_count?g_metrics.rssi_min:0);cJSON_AddNumberToObject(rs,"max",g_metrics.rssi_count?g_metrics.rssi_max:0);cJSON_AddNumberToObject(rs,"mean",g_metrics.rssi_count?(double)g_metrics.rssi_sum/g_metrics.rssi_count:0);cJSON*rh=cJSON_AddArrayToObject(rs,"histogram_minus_127_to_0");for(int i=0;i<128;i++)cJSON_AddItemToArray(rh,cJSON_CreateNumber(g_metrics.rssi_hist[i]));
cJSON*rt=cJSON_AddObjectToObject(r,"rtt");double mean=g_metrics.rtt_seen?(double)g_metrics.rtt_sum/g_metrics.rtt_seen:0;double variance=g_metrics.rtt_seen?(double)(g_metrics.rtt_sum_sq/g_metrics.rtt_seen)-mean*mean:0;cJSON_AddNumberToObject(rt,"sample_count",(double)g_metrics.rtt_seen);cJSON_AddNumberToObject(rt,"reservoir_count",g_metrics.rtt_count);cJSON_AddNumberToObject(rt,"min_us",g_metrics.rtt_seen?g_metrics.rtt_min:0);cJSON_AddNumberToObject(rt,"mean_us",mean);cJSON_AddNumberToObject(rt,"p50_us",pct(.5));cJSON_AddNumberToObject(rt,"p90_us",pct(.9));cJSON_AddNumberToObject(rt,"p95_us",pct(.95));cJSON_AddNumberToObject(rt,"p99_us",pct(.99));cJSON_AddNumberToObject(rt,"p999_us",pct(.999));cJSON_AddNumberToObject(rt,"max_us",g_metrics.rtt_max);cJSON_AddNumberToObject(rt,"stddev_us",sqrt(variance>0?variance:0));
cJSON_AddNumberToObject(rt,"jitter_mean_abs_delta_us",g_metrics.jitter_count?(double)g_metrics.jitter_sum/g_metrics.jitter_count:0);cJSON_AddNumberToObject(rt,"jitter_max_abs_delta_us",g_metrics.jitter_max);
cJSON*ss=cJSON_AddArrayToObject(r,"streams");for(int i=0;i<HARNESS_MAX_STREAMS;i++){stream_metric_t*m=&g_metrics.streams[i];if(!m->tx&&!m->rx)continue;cJSON*o=cJSON_CreateObject();cJSON_AddNumberToObject(o,"stream_id",i);u64(o,"tx_packets",m->tx);u64(o,"rx_packets",m->rx);u64(o,"missing",m->gaps);u64(o,"duplicate",m->duplicate);u64(o,"out_of_order",m->out_of_order);cJSON_AddItemToArray(ss,o);}return r;}
